import os
import re
import datetime

# --- CONFIGURATION ---
# 1. Where to look for Python files? (Current directory and subfolders)
SEARCH_DIR = "."
# 2. What to name the output LaTeX file?
OUTPUT_FILE = "model_docs.tex"

# --- REGEX PATTERNS ---
# Matches: # NOM: Symbol | Description | Unit (optional)
# Example: # NOM: C_{bat} | Battery Capacity | kWh
NOM_PATTERN = re.compile(r"#\s*NOM:\s*(.*?)\s*\|\s*(.*?)(?:\s*\|\s*(.*))?$")

# Matches: # CON: Name | Description
# Example: # CON: Energy Balance | Supply must equal demand
CON_PATTERN = re.compile(r"#\s*CON:\s*(.*?)\s*\|\s*(.*)$")


def scan_files():
    nomenclature = []
    constraints = []

    print(f"Scanning directory: {os.path.abspath(SEARCH_DIR)}")

    # Walk through all files recursively
    for root, dirs, files in os.walk(SEARCH_DIR):
        for filename in files:
            # Only look at Python files, ignore this script itself
            if filename.endswith(".py") and filename != "generate_docs.py":
                filepath = os.path.join(root, filename)

                with open(filepath, "r", encoding="utf-8") as f:
                    try:
                        lines = f.readlines()
                    except UnicodeDecodeError:
                        print(f"Skipping binary file: {filename}")
                        continue

                    for line_num, line in enumerate(lines):
                        # 1. Check for Nomenclature
                        nom_match = NOM_PATTERN.search(line)
                        if nom_match:
                            symbol = nom_match.group(1).strip()
                            desc = nom_match.group(2).strip()
                            unit = nom_match.group(3).strip() if nom_match.group(3) else ""

                            # Format Description + Unit
                            full_desc = desc
                            if unit:
                                full_desc += f" [{unit}]"

                            nomenclature.append((symbol, full_desc))

                        # 2. Check for Constraints
                        con_match = CON_PATTERN.search(line)
                        if con_match:
                            name = con_match.group(1).strip()
                            desc = con_match.group(2).strip()
                            # Escape underscores in LaTeX so "my_constraint" doesn't break
                            safe_name = name.replace("_", "\\_")
                            constraints.append((safe_name, desc))

    return nomenclature, constraints


def generate_latex(nomenclature, constraints):
    lines = []
    lines.append(f"% --- AUTOMATICALLY GENERATED ON {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')} ---")
    lines.append("% Do not edit this file manually. It is overwritten by GitHub Actions.")
    lines.append("")

    # --- PART 1: NOMENCLATURE ---
    lines.append("% --- NOMENCLATURE ENTRIES ---")
    # Sort alphabetically by symbol
    for symbol, desc in sorted(nomenclature, key=lambda x: x[0].lower()):
        # Write the standard nomencl entry
        lines.append(f"\\nomenclature{{{symbol}}}{{{desc}}}")

    lines.append("")

    # --- PART 2: CONSTRAINTS TABLE ---
    if constraints:
        lines.append("% --- CONSTRAINTS LIST ---")
        lines.append("\\section*{Model Constraints}")
        lines.append("\\begin{longtable}{p{0.35\\textwidth} p{0.6\\textwidth}}")
        lines.append("\\textbf{Constraint Name} & \\textbf{Description} \\\\")
        lines.append("\\hline")
        lines.append("\\endhead")

        # Sort alphabetically by Constraint Name
        for name, desc in sorted(constraints, key=lambda x: x[0].lower()):
            lines.append(f"\\texttt{{{name}}} & {desc} \\\\")

        lines.append("\\hline")
        lines.append("\\end{longtable}")

    # Write to file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✅ Success! Generated {OUTPUT_FILE}")
    print(f"   - {len(nomenclature)} Variables")
    print(f"   - {len(constraints)} Constraints")


if __name__ == "__main__":
    nom, con = scan_files()
    generate_latex(nom, con)